spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_lab?useSSL=false&serverTimeZone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    #jackson:
        #serialization:
           # write-dates-as-timestamps: false

    devtools:
        restart:
            enabled: true
server:
    port: 8080