name: Automatic Rollback

on:
  workflow_call:    # el CD lo llam
  workflow_dispatch: # ejecución manual

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: List and Revert to Last Successful Deploy
        run: |
          SERVICE_ID="${{ secrets.RENDER_SERVICE_ID }}"
          
          # 1. Obtener el ID del último deploy exitoso
          LAST_SUCCESS_ID=$(curl -s -X GET "https://api.render.com/v1/services/$SERVICE_ID/deploys?status=live&limit=1" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" | jq -r '.[0].id')

          echo "ID del último despliegue exitoso: $LAST_SUCCESS_ID"

          # 2. Ejecutar Rollback
          curl -s -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys/$LAST_SUCCESS_ID/rollback" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json"